name: SEIA daily feed

on:
  workflow_dispatch:
  schedule:
    - cron: '30 11 * * *'   # ~08:30 Chile (UTC-3)

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python seia_feed.py || true

      # Garantiza que SIEMPRE haya algo que publicar (evita 404 de Pages)
      - name: Ensure out/ exists and minimal files
        run: |
          mkdir -p out
          if [ ! -f out/feed.xml ]; then
            printf '%s\n' \
'<?xml version="1.0" encoding="UTF-8"?>' \
'<rss version="2.0">' \
'<channel>' \
'<title>SEIA - Ingresos recientes (no oficial)</title>' \
'<link>https://seia.sea.gob.cl/busqueda/buscarProyectoResumen.php</link>' \
'<description>Feed mínimo</description>' \
'<lastBuildDate>Wed, 01 Jan 2020 00:00:00 +0000</lastBuildDate>' \
'</channel>' \
'</rss>' > out/feed.xml
          fi
          if [ ! -f out/data.json ]; then
            printf '%s\n' '{"generated":"fallback","count":0,"items":[]}' > out/data.json
          fi

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
