name: SEIA daily feed

on:
  schedule:
    # GitHub usa UTC. 11:30 UTC ≈ 08:30 en Chile (UTC-3).
    - cron: '30 11 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python seia_feed.py

      - name: Publish to gh-pages
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git checkout -B gh-pages

          # Copiamos artefactos al raíz de gh-pages
          cp -f out/feed.xml feed.xml
          cp -f out/data.json data.json

          # Crear index.html (sin heredoc, usando printf para evitar errores YAML)
          if [ ! -f index.html ]; then
            printf '%s\n' \
'<!doctype html>' \
'<html lang="es">' \
'<head>' \
'  <meta charset="utf-8" />' \
'  <meta name="viewport" content="width=device-width,initial-scale=1" />' \
'  <title>SEIA Monitor</title>' \
'  <style>body{font-family:system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,Helvetica,Arial,sans-serif;max-width:760px;margin:40px auto;padding:0 16px;line-height:1.5} a{word-break:break-all} code{background:#f4f4f4;padding:2px 6px;border-radius:4px}</style>' \
'</head>' \
'<body>' \
'  <h1>seia-monitor</h1>' \
'  <p>Feeds generados automáticamente:</p>' \
'  <ul>' \
'    <li><a href="./feed.xml">RSS</a></li>' \
'    <li><a href="./data.json">JSON</a></li>' \
'  </ul>' \
'</body>' \
'</html>' \
> index.html
          fi

          git add feed.xml data.json index.html
          git commit -m "Update feed $(date -u +'%Y-%m-%d %H:%M:%S')" || echo "Nothing to commit"
          git push -f origin gh-pages
