      - name: Publish to gh-pages
        run: |
          set -e
          git fetch origin
          git checkout -B gh-pages

          echo "Archivos en out/:"
          ls -la out || true

          # Copiar siempre desde out/ al root de la rama gh-pages
          if [ -f out/feed.xml ]; then cp out/feed.xml ./feed.xml; fi
          if [ -f out/data.json ]; then cp out/data.json ./data.json; fi
          if [ -f out/debug_sample.html ]; then cp out/debug_sample.html ./debug_sample.html; fi

          echo "Archivos en la raíz de gh-pages:"
          ls -la

          git add feed.xml data.json debug_sample.html 2>/dev/null || true
          git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" \
            commit -m "Update feed $(date -u +'%Y-%m-%d %H:%M:%S')" || echo "Nothing to commit"

          git push -f origin gh-pages
