name: SEIA daily feed

on:
  schedule:
    - cron: '30 11 * * *'   # ~08:30 Chile (UTC-3)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python seia_feed.py

      # ====== CLAVE: guardar 'out/' en carpeta temporal ANTES de cambiar de rama ======
      - name: Stage site to temp dir
        run: |
          set -e
          echo "Workspace root:"
          ls -la
          echo
          echo "./out contents:"
          ls -la out || true
          mkdir -p /tmp/site
          cp -r out/* /tmp/site/ || true
          echo "/tmp/site contents:"
          ls -la /tmp/site || true

      - name: Publish to gh-pages
        run: |
          set -e
          git fetch origin
          git checkout -B gh-pages

          echo "On gh-pages BEFORE copy:"
          ls -la

          # Copiar desde el staging temporal a la raíz de gh-pages
          cp -r /tmp/site/* . || true

          # (Opcional) eliminar carpeta 'out' si quedó comiteada de intentos anteriores
          rm -rf out || true

          echo "On gh-pages AFTER copy:"
          ls -la

          git add -A
          git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" \
            commit -m "Update feed $(date -u +'%Y-%m-%d %H:%M:%S')" || echo "Nothing to commit"

          git push -f origin gh-pages
